apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle  
  awsElasticBlockStore:
    volumeID: vol-0c4587c6068bd4f45
    fsType: ext4

