apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus-exporter-svc
spec:
  type: NodePort
  ports:
  - port: 9113
    targetPort: 9113
  selector:
    app: nginx-prometheus-exporter

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9113"
      labels:
        app: nginx-prometheus-exporter
    spec:
      containers:
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
        - --nginx.scrape-uri=http://nginx-svc:8080/nginx_status
        ports:
        - containerPort: 9113
          name: prometheus