apiVersion: v1
kind: Service
metadata:
  name: nginx 
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 8080  # External port
      targetPort: 80  # Port Nginx is listening on inside the container
      protocol: TCP

